name: Build ThunderInterfaces on MacOS

on:
  workflow_dispatch:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  Thunder:
    uses: rdkcentral/Thunder/.github/workflows/MacOS build template.yml@master

  ThunderInterfaces:
    needs: Thunder
    uses: rdkcentral/ThunderInterfaces/.github/workflows/MacOS build template.yml@master

  # ThunderClientLibraries:
  #   needs: ThunderInterfaces
  #   uses: rdkcentral/ThunderClientLibraries/.github/workflows/Linux build template.yml@master

  # ThunderNanoServices:
  #   needs: ThunderInterfaces
  #   uses: rdkcentral/ThunderNanoServices/.github/workflows/Linux build template.yml@master

  # ThunderNanoServicesRDK:
  #   needs: ThunderInterfaces
  #   uses: WebPlatformForEmbedded/ThunderNanoServicesRDK/.github/workflows/Linux build template.yml@master
