name: Build ThunderInterfaces on Linux (R4_4)

permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    branches: ["development/actions-r4_4"] # TO-DO: change to R4_4 when development is over
  pull_request:
    branches: ["R4_4"]

jobs:
  Thunder:
    uses: rdkcentral/Thunder/.github/workflows/Linux build template.yml@development/actions-r4_4 # TO-DO: change to R4_4 when development is over

  ThunderInterfaces:
    needs: Thunder
    uses: ./.github/workflows/Linux build template.yml
